---
- include: uninstall.yml

- name: Delete MariaDB Conf/Data Directories
  file: path={{ item }} state=absent
  with_items:
    - /var/lib/mysql
    - /etc/my.cnf.d
  when: ansible_fqdn in groups['mariadb']

- name: Delete HAproxy health check script
  file: path={{ item }} state=absent
  with_items:
    - /usr/share/mysql/mysqlchk.sh
    - /etc/xinetd.d/mysqlchk
  when: mariadb_ha and ansible_fqdn in groups['mariadb']

- name: restart xinetd
  service: name=xinetd state=restarted
  when: mariadb_ha and ansible_fqdn in groups['mariadb']

- name: Delete replication-manager config File
  file: path={{ item }} state=absent
  with_items:
    - /etc/replication-manager/config.toml
  when: mariadb_ha and ansible_fqdn in groups['replication_manager']